# 7 Solving systems of linear equations

When you think of algebra, you probably think of problems that require “solving for x.” For instance, you probably spent quite a bit of time in algebra class learning to solve equations like 3x**2 + 2x + 4 = 0; that is, figuring out what value or values of x make the equation true.

Linear algebra, being a branch of algebra, has the same kinds of computational questions. The difference is that what you want to solve for may be a vector or matrix rather than a number.

I’m going to cover the most important class of linear algebra problems you’ll see in the wild: systems of linear equations. These problems boil down to finding points where lines, planes, or their higher dimensional analogies intersect.

## 7.1 Designing an arcade game

To get started, we model the entities of the game — **the spaceship**, **the laser**, and the **asteroids** — and show how to render them onscreen.

### 7.1.1 Modeling the game

In [127]:
# PolygonModel class represents a game entity (the ship or an asteroid) that keeps its shape but can translate or rotate.
import vectors
from random import *
from math import pi, sqrt, cos, sin, atan2

class PolygonModel():
    def __init__(self, points):
        self.points = points
        self.rotation_angle = 0
        self.x = 0
        self.y = 0

In [14]:
class Ship(PolygonModel):
    def __init__(self):
        super().__init__([(0.5,0), (-0.25,0.25), (-0.25,-0.25)])

In [15]:
class Asteroid(PolygonModel):
    def __init__(self):
        sides = randint(5,9)
        vs = [vectors.to_cartesian((uniform(0.5,1.0), 2*pi*i/sides)) 
                for i in range(0, sides)]

### 7.1.2 Rendering the game

In [31]:
ship = Ship()

asteroid_count = 10
asteroids = [Asteroid() for _ in range(0, asteroid_count)]

for ast in asteroids:
    ast.x = randint(-9,9)
    ast.y = randint(-9,9)

In [137]:
# my implemetation 
def to_pixels(coord_range_x, coord_range_y, pix_range_x, pix_range_y, x, y):
    coord_x_start, coord_x_stop = coord_range_x
    coord_y_start, coord_y_stop = coord_range_y
    pix_x_start, pix_x_stop = pix_range_x
    pix_y_start, pix_y_stop = pix_range_y
    
    s_x = (coord_x_stop - x) / (coord_x_stop - coord_x_start)
    s_y = 1 - ((coord_y_stop - y) / (coord_y_stop - coord_y_start))

    x_pix = s_x * pix_x_start + (1 - s_x) * pix_x_stop
    y_pix = s_y * pix_y_start + (1 - s_y) * pix_y_stop

    return (x_pix, y_pix)

In [114]:
pixs = to_pixel((-10,10), (-10,10), (0,400), (0,400), -10, -10)
pixs

(0.0, 400.0)

In [115]:
GREEN = (0, 255, 0) 
def draw_poly(screen, polygon_model, color=GREEN): 
    pixel_points = [to_pixels(x,y) for x,y in polygon_model.transformed()] 
    pygame.draw.aalines(screen, color, True, pixel_points, 10) #<1>

### 7.1.3 Shooting the laser

In [116]:
class Ship(PolygonModel):
    def __init__(self):
        super().__init__([(0.5,0), (-0.25,0.25), (-0.25,-0.25)])

    def laser_segment(self):
        dist = 20 * sqrt(2)
        x,y = self.transformed()[0]
        return (
                (x,y), 
                (x + dist * cos(self.rotation_angle)), 
                (y + dist * sin(self.rotation_angle))
                )

In [ ]:
laser = ship.laser_segment() #<1> 
     
    keys = pygame.key.get_pressed() #<2> 
     if keys[pygame.K_SPACE]: 
         draw_segment(*laser) 
 
         for asteroid in asteroids: 
             if asteroid.does_intersect(laser): #<3> 
                 asteroids.remove(asteroid)

### 7.1.4 Exercises

**Exercise 7.1:** Implement a transformed() method on the PolygonModel that returns the points of the model translated by the object’s x and y attributes and rotated by its rotation_angle attribute.

In [129]:
class PolygonModel():
    def __init__(self, points):
        self.points = points
        self.rotation_angle = 0
        self.x = 0
        self.y = 0

    # Make sure to apply the rotation first; Order of operation
    def transformed(self):
        rot = [vectors.rotate2d(self.rotation_angle, point) for point in self.points]
        return [vectors.add((self.x, self.y), point) for point in rot]
    


Exercise 7.2: Write a function to_pixels(x,y) that takes a pair of x- and y-coordinates in the square where -10 < x < 10 and -10 < y < 10 and maps them to the corresponding PyGame x and y pixel coordinates, each ranging from 0 to 400.


In [136]:
# my implemetation 
def to_pixels(coord_range_x, coord_range_y, pix_range_x, pix_range_y, x, y):
    coord_x_start, coord_x_stop = coord_range_x
    coord_y_start, coord_y_stop = coord_range_y
    pix_x_start, pix_x_stop = pix_range_x
    pix_y_start, pix_y_stop = pix_range_y
    
    s_x = (coord_x_stop - x) / (coord_x_stop - coord_x_start)
    s_y = 1 - ((coord_y_stop - y) / (coord_y_stop - coord_y_start))

    x_pix = s_x * pix_x_start + (1 - s_x) * pix_x_stop
    y_pix = s_y * pix_y_start + (1 - s_y) * pix_y_stop

    return (x_pix, y_pix)

In [135]:
pixs = to_pixel((-10,10), (-10,10), (0,400), (0,400), 10, -10)
pixs

(400.0, 400.0)

In [138]:
width, height = 400, 400
def to_pixels(x,y):
    return (width/2 + width * x / 20, height/2 - height * y / 20)

## 7.2 Finding intersection points of lines

### 7.2.1 Choosing the right formula for a line

### 7.2.2 Finding the standard form equation for a line

### 7.2.3 Linear equations in matrix notation

TODO: go over chapter_5 again

We’re talking about a bunch of different concepts at once here: linear equations, linear combinations, matrices, and linear transformations. The point is that this is a fundamental kind of problem in linear algebra; you can look at it from several different perspectives. In the next section, we’ll see how they all fit together, but for now, let’s focus on solving the problem at hand.

### 7.2.4 Solving linear equations with NumPy

In [3]:
import numpy as np

matrix = np.array(((-1,1), (1,2)))
output = np.array((0,8))
np.linalg.solve(matrix, output)

array([2.66666667, 2.66666667])

This is perhaps the most important computational task in linear algebra: starting with a matrix `A`, and a vector `w`, and finding the vector `v` such that `Av` = w. Such a vector gives the solution to a system of linear equations represented by `A` and `w`.

### 7.2.5 Deciding whether the laser hits an asteroid

First, we need to convert the given line segments from pairs of endpoint vectors to linear equations in standard form. (u1, u1) --> (ax + by = c)

Next, given two segments, each represented by its pair of endpoint vectors, we want to find out where their lines intersect.



In [ ]:
def intersection(u1,u2,v1,v2): 
     a1, b1, c1 = standard_form(u1,u2) 
     a2, b2, c2 = standard_form(v1,v2) 
     m = np.array(((a1,b1),(a2,b2))) 
     c = np.array((c1,c2)) 
     return np.linalg.solve(m,c)

The output is the point where the two lines on which the segments lie intersect. But this point might not lie on either of the segments as shown in figure 7.17.

To detect whether the two segments intersect, we need to check that the intersection point of their lines lies between the two pairs of endpoints. We can check that using distances.

In [ ]:
def do_segments_intersect(s1,s2): 
    u1,u2 = s1 
    v1,v2 = s2 
    d1, d2 = distance(*s1), distance(*s2) #<1> 
    x,y = intersection(u1,u2,v1,v2) #<2> 
    return (distance(u1, (x,y)) <= d1 and #<3> 
            distance(u2, (x,y)) <= d1 and 
            distance(v1, (x,y)) <= d2 and 
            distance(v2, (x,y)) <= d2)

Finally, we can write the does_intersect method by checking whether do_segments_intersect returns True for the input segment and any of the edges of the (transformed) polygon:

In [ ]:
class PolygonModel(): 
     ... 
     def does_intersect(self, other_segment):
        for segment in self.segments():
            if do_segments_intersect(other_segment,segment):
                return True
        return False

### 7.2.6 Identifying unsolvable systems


Let me leave you with one final admonition: not every system of linear equations in 2D can be solved!

Where we run into trouble is when the lines are parallel, meaning the lines never intersect (or they’re the same line!) as shown in figure 7.19.



In the first case, there are zero intersection points, while in the second, there are infinitely many intersection points—every point on the line is an intersection point. Both of these cases are problematic computationally because our code demands a single, unique result. If we try to solve either of these systems with NumPy, for instance, the system consisting of 2x + y = 6 and 4x + 2y = 8, we get an exception:

In [2]:
import numpy as np 
m = np.array(((2,1),(4,2))) 
v = np.array((6,4)) 
np.linalg.solve(m,v) 

LinAlgError: Singular matrix

NumPy points to the matrix as the source of the error. The matrix is called a singular matrix, meaning there is no unique solution to the linear system.

We’ll philosophize more about singular matrices later, but for now you can see that the rows (2, 1) and (4, 2) and the columns (2, 4) and (1, 2) are both parallel and, therefore, linearly dependent. This is the key clue that tells us the lines are parallel and that the system does not have a unique solution. Solvability of linear systems is one of the central concepts in linear algebra; it closely relates to the notions of linear independence and dimension. We discuss that in the last two sections of this chapter.

In [ ]:
def do_segments_intersect(s1,s2): 
     u1,u2 = s1 
     v1,v2 = s2 
     l1, l2 = distance(*s1), distance(*s2) 
     try: 
         x,y = intersection(u1,u2,v1,v2) 
         return (distance(u1, (x,y)) <= l1 and 
                 distance(u2, (x,y)) <= l1 and 
                 distance(v1, (x,y)) <= l2 and 
                 distance(v2, (x,y)) <= l2) 
     except np.linalg.linalg.LinAlgError: 
         return False

### 7.2.7 Exercises

**Exercise 7.11:** Write a Python function standard_form that takes two vectors v1 and v2 and finds the line ax + by = c passing through both of them. Specifically, it should output the tuple of constants (a, b, c).


In [21]:
def standard_form(v1,v2):
    x1, y1 = v1
    x2, y2 = v2

    a = y2 - y1
    b = x1 - x2
    c = x1 * y2 - x2 * y1

    return (a,b,c)

**Mini-project 7.12:** For each of the four distance checks in do_segments_intersect, find a pair of line segments that fail one of the checks but pass the other three checks.

In [ ]:
def segment_checks(s1,s2):
    u1,u2 = s1
    v1,v2 = s2
    l1, l2 = distance(*s1), distance(*s2)
    x,y = intersection(u1,u2,v1,v2)
    return [
        distance(u1, (x,y)) <= l1,
        distance(u2, (x,y)) <= l1,
        distance(v1, (x,y)) <= l2,
        distance(v2, (x,y)) <= l2
    ]

**Exercise 7.13:** For the example laser line and asteroid, confirm the does_intersect function returns True. (Hint: use grid lines to find the vertices of the asteroid and build a PolygonModel object representing it.)

In [10]:
from asteroids import PolygonModel

asteroid1 = PolygonModel(([(2,7), (1,5), (2,3), (4,2), (6,2), (7,4), (6,6), (4,6)]))
asteroid1.does_intersect([(0,0),(7,7)])

True

In [11]:
asteroid1.does_intersect([(0,0),(0,7)])

False

**Exercise 7.14:** Write a does_collide(other_polygon) method to decide whether the current PolygonModel object collides with another other_polygon by checking whether any of the segments that define the two are intersecting. This could help us decide whether an asteroid has hit the ship or another asteroid.

In [19]:
def segments(points):
    return [(points[i], points[(i+1)%len(points)]) for i in range(0,len(points))]

In [20]:
p = [(2,7), (1,5), (2,3), (4,2), (6,2), (7,4), (6,6), (4,6)]
segments(p)

[((2, 7), (1, 5)),
 ((1, 5), (2, 3)),
 ((2, 3), (4, 2)),
 ((4, 2), (6, 2)),
 ((6, 2), (7, 4)),
 ((7, 4), (6, 6)),
 ((6, 6), (4, 6)),
 ((4, 6), (2, 7))]

In [22]:
def standard_form(v1,v2):
    x1, y1 = v1
    x2, y2 = v2

    a = y2 - y1
    b = x1 - x2
    c = x1 * y2 - x2 * y1

    return (a,b,c)

In [24]:
def intersection(s1, other_seg):
    a1, b1, c1 = standard_form(s1)
    a2, b2, c2 = standard_form(other_seg)
    m = np.array(((a1,b1), (a2,b2)))
    c = np.array((c1,c2))
    return np.linalg.solve(m,c)

In [ ]:
def does_collide(points, other_points):
    seg = segments(points)
    other_seg = segments(other_points)

    for segment in seg:
        for other_segment in other_seg:
            pass
            #TODO write the whole game from scratch!


## TODO: REDO CHAPTER 5 -- MATRIX!

## 7.3 Generalizing linear equations to higher dimensions

### 7.3.1 Representing planes in 3D

### 7.3.2 Solving linear equations in 3D

### 7.3.3 Studying hyperplanes algebraically

### 7.3.4 Counting dimensions, equations, and solutions

### 7.3.5 Exercises


**Mini-project 7.19:** Write a Python function that takes three 3D points as inputs and returns the standard form equation of the plane that they lie in. For instance, if the standard form equation is ax + by + cz = d, the function could return the tuple (a, b, c, d).

In [3]:
from vectors import *

def plane_equation(p1,p2,p3):
    parallel1 = subtract(p2,p1)
    parallel2 = subtract(p3,p1)
    a,b,c = cross(parallel1, parallel2)
    d = dot((a,b,c), p1)
    return a,b,c,d

In [5]:
plane_equation((1,1,1), (3,0,0), (0,3,0))

(3, 3, 3, 9)

**Mini-project 7.26:** In any number of dimensions, there is an identity matrix that acts as the identity map. That is, when you multiply the n-dimensional identity matrix I by any vector v, you get the same vector v as a result; therefore, Iv = v.

This means that Iv = w is an easy system of linear equations to solve: one possible answer for v is v = w. The idea of this mini-project is that you can start with a system of linear equations, Av = w, and multiply both sides by another matrix B such that (BA) = I. If that is the case, then you have (BA)v = Bw and Iv = Bw or v = Bw. In other words, if you have a system Av = w, and a suitable matrix B, then Bw is the solution to your system. This matrix B is called the inverse matrix of A.


In [5]:
m = np.array(((2,0,0), (0,2,0), (0,0,2)))
v = np.array((1,1,1))
mi = np.linalg.inv(m)
np.matmul(m, mi)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
matrix = np.array(((1,1,-1),(0,2,-1),(1,0,1)))
vector = np.array((-1,3,2))
inverse = np.linalg.inv(matrix)
inverse

array([[ 0.66666667, -0.33333333,  0.33333333],
       [-0.33333333,  0.66666667,  0.33333333],
       [-0.66666667,  0.33333333,  0.66666667]])

In [13]:
np.matmul(inverse, matrix)

array([[ 1.00000000e+00,  1.11022302e-16, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [14]:
np.matmul(inverse, vector)

array([-1.,  3.,  3.])